# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(null=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True, verbose_name='上次登录IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_ip',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True, verbose_name='注册IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='this_login_date',
            field=models.DateTimeField(null=True, verbose_name='本次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='this_login_ip',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True, verbose_name='本次登录IP'),
        ),
    ]
