# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrecord',
            name='type',
            field=models.PositiveSmallIntegerField(default=0, help_text='0:接口自动记录类型；1:每月汇总(每月1号自动汇总上个月流量统计并清除上月数据)', verbose_name='类型'),
        ),
    ]
