# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_trafficrecord_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficrecord',
            name='type',
            field=models.PositiveSmallIntegerField(default=0, help_text='0:接口自动记录类型；1/2 日/月汇总数据', verbose_name='类型'),
        ),
    ]
