# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import user.models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170227_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'ordering': ['-id'], 'verbose_name': '邀请码', 'verbose_name_plural': '邀请码'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['sort', 'id'], 'verbose_name': '节点', 'verbose_name_plural': '节点'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='node',
            name='sort',
            field=models.SmallIntegerField(default=0, help_text='小的在前面', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=user.utils.gen_invite_code, max_length=127, unique=True, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='node',
            name='obfs',
            field=models.CharField(choices=[('plain', 'plain：不混淆，无参数'), ('tls1.2_ticket_auth', 'tls1.2_ticket_auth：伪装为tls请求。参数配置与http_simple一样'), ('http_simple', 'http_simple：简易伪装为http get请求'), ('http_post', 'http_post：与http_simple绝大部分相同，POST伪装方式'), ('tls1.2_ticket_auth_compatible', 'tls1.2_ticket_auth_compatible：兼容版'), ('http_simple_compatible', 'http_simple_compatible：兼容版'), ('http_post_compatible', 'http_post_compatible：兼容版')], default='tls1.2_ticket_auth_compatible', help_text='混淆推荐：如果QoS在你的地区明显，混淆建议在http_simple与tls1.2_ticket_auth中选择，具体选择可以通过自己的试验得出。如果选择混淆后反而变慢，那么混淆请选择plain。如果你不在乎QoS，但担心你的个人vps能不能持久使用，那么混淆选择plain或tls1.2_ticket_auth，协议选择auth_aes128_md5或auth_aes128_sha1', max_length=127, verbose_name='混淆插件'),
        ),
        migrations.AlterField(
            model_name='node',
            name='protocol',
            field=models.CharField(choices=[('origin', 'origin：原版协议'), ('auth_sha1_v4', 'auth_sha1_v4：较高安全性，有宽松的时间校对要求，混淆强度大'), ('auth_aes128_md5', 'auth_aes128_md5：最高安全性，有宽松的时间校对要求，计算量相对高一些，混淆强度较大'), ('auth_aes128_sha1', 'auth_aes128_sha1：最高安全性，有宽松的时间校对要求，计算量相对高一些，混淆强度较大'), ('auth_sha1_v4_compatible', 'auth_sha1_v4_compatible，兼容版')], default='auth_sha1_v4_compatible', help_text='协议推荐：协议用auth_aes128_md5或auth_aes128_sha1最佳（但是不支持原版SS协议），此时即使使用rc4加密亦可，混淆随意；_compatible后缀表示兼容原版SS协议', max_length=63, verbose_name='协议插件'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ssh_port',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='SSH端口号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='avatar1.png', max_length=63, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='port',
            field=models.PositiveSmallIntegerField(default=user.models.get_usefull_port, unique=True, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='user',
            name='this_login_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='本次登录时间'),
        ),
    ]
