# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170312_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficrecord',
            name='create_date',
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='summary_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='汇总产生日期'),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='产生的时间'),
        ),
    ]
