# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170303_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(default=user.utils.gen_api_key, editable=False, max_length=63, primary_key=True, serialize=False, verbose_name='主键、API Key'),
        ),
    ]
