# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170312_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrecord',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='产生的日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='create_time',
            field=models.TimeField(auto_now_add=True, verbose_name='产生的时间点'),
        ),
    ]
