# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170311_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=63, verbose_name='行为类型')),
                ('remark', models.TextField(null=True, verbose_name='行为备注')),
                ('meta', models.CharField(max_length=1023, null=True, verbose_name='一些信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='产生时间')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '用户动作记录',
                'verbose_name_plural': '用户动作记录',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='create_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_code_set', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='show_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公开显示时间'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='used_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_code_set', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
