# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170303_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='节点IPv6地址'),
        ),
        migrations.AlterField(
            model_name='node',
            name='method',
            field=models.CharField(choices=[('rc4-md5', 'rc4-md5'), ('chacha20', 'chacha20'), ('aes-256-cfb', 'aes-256-cfb'), ('aes-192-cfb', 'aes-192-cfb'), ('aes-128-cfb', 'aes-128-cfb'), ('salsa20', 'salsa20'), ('rc4', 'rc4'), ('table', 'table')], default='chacha20', max_length=63, verbose_name='节点加密方式'),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('ON-LINE', '正常'), ('OFF-LINE', '离线'), ('BANDWIDTH-OVER', '流量用完'), ('ATTACKED', '被攻击中'), ('INIT', '初始化中'), ('MAINTAIN', '维护中'), ('OUT', '下线')], default='INIT', max_length=63, verbose_name='节点状态'),
        ),
    ]
