# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170312_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='remark_for_admin',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='管理员备注'),
        ),
    ]
