# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170311_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecord',
            name='ip',
            field=models.CharField(max_length=255, null=True, verbose_name='ip地址'),
        ),
    ]
