# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170303_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('slug', models.CharField(help_text='请使用字母、数字、下划线、中划线组成，不可重复', max_length=63, primary_key=True, serialize=False, unique=True, validators=(django.core.validators.RegexValidator('[\\w-]+'),), verbose_name='标识')),
                ('name', models.CharField(max_length=63, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '节点标签',
                'verbose_name_plural': '节点标签',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='location',
            field=models.CharField(default='a', max_length=127, verbose_name='节点位置'),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.NodeTag', verbose_name='标签集合'),
        ),
    ]
