# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 06:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170304_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='请使用字母、数字、下划线、中划线组成，不可重复', max_length=255, unique=True, validators=(django.core.validators.RegexValidator('[\\w-]+'),), verbose_name='内容标识Slug')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('PUBLISHED', '已发布'), ('DRAFT', '草稿')], default='DRAFT', max_length=31, verbose_name='文章状态')),
                ('abstract', models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前54个字符', max_length=63, null=True, verbose_name='摘要')),
                ('topped', models.BooleanField(default=False, verbose_name='置顶')),
            ],
            options={
                'ordering': ['-topped', '-last_modified_time'],
            },
        ),
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(max_length=127, verbose_name='节点位置'),
        ),
    ]
