# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_node_remark_for_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='flag',
            field=models.CharField(blank=True, default=None, help_text='参考：https://github.com/lipis/flag-icon-css', max_length=63, verbose_name='节点国旗图标'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='traffic',
            field=models.BigIntegerField(default=6442450944, help_text='以最小的字节B为单位', verbose_name='流量'),
        ),
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(max_length=127, verbose_name='节点地理位置'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ssh_port',
            field=models.PositiveSmallIntegerField(default=22, help_text='用于发送远程命令', verbose_name='SSH端口号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bind_email',
            field=models.BooleanField(default=False, verbose_name='是否已验证邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='transfer_enable',
            field=models.BigIntegerField(default=6442450944, verbose_name='每月流量限额'),
        ),
    ]
