# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170305_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-topped', '-last_modified_time'], 'verbose_name': '文章内容', 'verbose_name_plural': '文章内容'},
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('ANNOUNCE', '站内通告'), ('PAGE', '页面'), ('OTHER', '其他类型')], default='ANNOUNCE', max_length=31, verbose_name='内容类型'),
        ),
    ]
