# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import xsadmin.settings


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170305_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=xsadmin.settings.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('rename', models.BooleanField(default=True, help_text='如果选中，则会随机重命名；否则不会重命名，但是有覆盖已有同名文件风险。', verbose_name='是否重命名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
