# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.BigIntegerField(default=0, verbose_name='上传流量')),
                ('d', models.BigIntegerField(default=0, verbose_name='下载流量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='产生时间')),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='流量倍率')),
            ],
            options={
                'verbose_name': '流量记录',
                'verbose_name_plural': '流量记录',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded'], 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AddField(
            model_name='node',
            name='last_api_request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='最后调用远程API的时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Node', verbose_name='所属节点'),
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属者'),
        ),
    ]
